// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dembgyirxfjkdcldjeeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbWJneWlyeGZqa2RjbGRqZWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTY5MTUsImV4cCI6MjA2ODY5MjkxNX0.bhC0JgRnoVlLh9ZHc5EgJa7Q3kWZZGy4gSd5yXO1BbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});